#!/bin/bash

#sudo /usr/local/sbin/mc single_xml/max_period_offset.xml
#sudo /usr/local/sbin/mc single_xml/min_offset_no_peri.xml
#sudo /usr/local/sbin/mc single_xml/min_offset_with_peri.xml
#sudo /usr/local/sbin/mc single_xml/async_no_period.xml
sudo /usr/local/sbin/mc single_xml/async_period.xml 3
#sleep 0.5
#sudo /usr/local/sbin/mc single_xml/disable_all.xml

#sudo /usr/local/sbin/mc single_xml/enable_all.xml
