#!/bin/bash
domid=0;
domid=$2

transid=-1;
transid=$3;

if [[ "$domid" -eq 0 ]]; then
    echo 'enter domid'
    exit 0
fi
if [[ "$transid" -eq -1 ]]; then
    echo 'enter transtion id'
    exit 0
fi


#sudo /usr/local/sbin/mc single_xml/max_period_offset.xml
#sudo /usr/local/sbin/mc single_xml/min_offset_no_peri.xml
#sudo /usr/local/sbin/mc single_xml/min_offset_with_peri.xml
#sudo /usr/local/sbin/mc single_xml/async_no_period.xml
sudo /usr/local/sbin/mc single_xml/v$1/async_period.xml $3 $2
#sleep 0.5
#sudo /usr/local/sbin/mc single_xml/disable_all.xml

#sudo /usr/local/sbin/mc single_xml/enable_all.xml
